#!/bin/sh -xe
exec 2>&1

# change to code path
cd {{pkg.svc_var_path}}

# execute gunicorn from venv
exec venv/bin/gunicorn --workers={{cfg.number_of_workers}} app:app --bind {{cfg.bind_host}}:{{cfg.bind_port}}

